### ISSUE TITLE
Which GPL license?

### ISSUE THREAD

**Issue by jluttine** [delfick/nose-of-yeti#11]
Which GPL license is this package released under?
https://github.com/delfick/nose-of-yeti/blob/9e535cab57f6435b515a8efc6cdaf9538f1d5f5a/setup.py#L15

**Comment by delfick** [comment]
Good question!

It seems I wrote that in the initial commit in 2010 when I didn't know any better :)

I'll change it to MIT license to be in line with what I usually do these days.

**Comment by jluttine** [comment]
Great, thanks a lot! If you could do a new release with that license, it'd be awesome, so that there's an actual release with a proper license. And if you could tag the release in GitHub and/or include tests in the PyPI source tarball, that'd be great too, but just a suggestion (as I suggested for nose-focus too).

**Comment by delfick** [comment]
Oh yeah, for sure!

After getting permission from the other contributors (@cgspeck, @lmartinking and @hltbra) I have changed the license to MIT, updated the version to 1.8 and made a Github release

:)

**Comment by jluttine** [comment]
Awesome! Thanks!!

**Comment by delfick** [comment]
no probs :)
