### ISSUE TITLE
No git tags for 2.x versions

### ISSUE THREAD

**Issue by felixonmars** [delfick/nose-of-yeti#14]
It would be nice to keep PyPI releases and git tags in sync :)

**Comment by delfick** [comment]
Hi,

Historically I never tag versions for any of my projects. But recently every time I touch one of my projects I've been adding github actions for tests, lints and releases. And the releases action does github releases and git tags. Given your other issue, I imagine this project will be next and start getting those tags :)

**Comment by felixonmars** [comment]
That's great, thanks!

**Comment by delfick** [comment]
noseOfYeti is using github actions now :)

I've made a 2.0.3 release so that there is a release with a git tag and github release entry. It has no actual changes from 2.0.2 :)

**Comment by felixonmars** [comment]
Thank you!
