### ISSUE TITLE
Nice to find this here

### ISSUE THREAD

**Issue by fmeyer** [delfick/nose-of-yeti#15]
I'm glad someone picked this up; I remember feeling that ruby had a great idiom to functional express tests that could be used elsewhere, 

I have only one observation about attribution. I came up with the idea that yielded a simple post 
https://web.archive.org/web/20120405004819/http://fmeyer.org/en/writing-a-DSL-with-python.html and this repo https://github.com/fmeyer/pydsl that never worked, @hltbra pick up from that and wrote Yeti alone, so he has to be credited as well :)

**Comment by delfick** [comment]
Hello!

> I'm glad someone picked this up

I love what the codec idea has given me over the decade I've been working on noseOfYeti. Though the shenanigans around making it work with black/pylama/mypy are less than ideal :(

>  I came up with the idea that yielded a simple post

nice :)

>  @hltbra pick up from that and wrote Yeti alone, so he has to be credited as well :)

yeah right, how about this change ? https://github.com/delfick/nose-of-yeti/pull/16 :)

**Comment by fmeyer** [comment]
lgtm :)

**Comment by delfick** [comment]
:D
