### ISSUE TITLE
Version 2.4.4 sdist missing most contents

### ISSUE THREAD

**Issue by kitterma** [delfick/nose-of-yeti#19]
If you compare the contents of the sdist tarball from either [Pypi](https://files.pythonhosted.org/packages/01/13/7e5ea93d446711ba3dfb11cd54df065143ef5685cfb15c2348b87e41ffaf/noseofyeti-2.4.4.tar.gz) or [GitHub](https://github.com/delfick/nose-of-yeti/releases/download/release-2.4.4/noseofyeti-2.4.4.tar.gz) with the automatically generated tarball from the [GitHub tag](https://github.com/delfick/nose-of-yeti/archive/refs/tags/release-2.4.4.zip), you'll see almost nothing is there in the first two.  Please bump the version and re-release a full sdist (I depend on them to package this for Debian and I would imagine I'm not the only one).

**Comment by delfick** [comment]
ah yeah, can do.

Do you use the tooling that comes in my code (the venvstarter stuff in
tools, and test.sh, lint, format, etc) or do you only also need the tests
folder?

**Comment by kitterma** [comment]
On January 20, 2024 10:08:34 PM UTC, Stephen Moore ***@***.***> wrote:
>ah yeah, can do.
>
>Do you use the tooling that comes in my code (the venvstarter stuff in
>tools, and test.sh, lint, format, etc) or do you only also need the tests
>folder?

No.  I don't need tools and the other stuff, but note that currently even the noseOfYeti directory is missing.

Thanks,

Scott K

**Comment by delfick** [comment]
yeah, that's bad!

It would appear I messed up the pyproject.toml when I converted to hatchling and got the case wrong

have 

```
[tool.hatch.build.targets.sdist]
include = [
    "/noseofyeti",
]
```

instead of 

```
[tool.hatch.build.targets.sdist]
include = [
    "/noseOfYeti",
]
```

oops.

**Comment by delfick** [comment]
<img width="478" alt="Screenshot 2024-01-21 at 11 37 26 am" src="https://github.com/delfick/nose-of-yeti/assets/109301/91e7847a-9e36-4942-9877-67f448b4ab6a">
that's better, thanks for letting me know about it!

**Comment by delfick** [comment]
though

```
pip install noseOfYeti -t blah --no-binary noseOfYeti
``` 

doesn't work because of the .pth shenanigans. deep sigh

**Comment by delfick** [comment]
ok, 2.4.6 works 

(assuming pip uses wheel with the sdist, I feel that's a reasonable assumption)

**Comment by kitterma** [comment]
That took care of it.  Thanks.

**Comment by delfick** [comment]
you're welcome!
